/*
-------------------------------------------------------------------
    NAMA    : M. INDRA GUNAWAN
    NRP     : 152020068
    KELAS   : BB Project Tugas Besar
-------------------------------------------------------------------
 */
package View;
import com.Admin;
import Execute.ExecAdmin;
import com.ConvertAdminToObject;
import com.Barang;
import com.ConvertBarangToObject;
import Execute.ExcuteBarang;
import Execute.ExecutCustomer;
import com.ConvertCustomerToObject;
import com.ConvertTransaksiToObject;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
public class GuiAdmin extends javax.swing.JFrame {

    public GuiAdmin() {
        initComponents();
        setDataBarang();
        setDataAdmin();
        setDataCustomer();
        setDataTransaksi();
        
        this.setLocationRelativeTo(null);
    }
    private void setDataBarang(){
        ConvertBarangToObject cbto = new ConvertBarangToObject();
        String [] [] dataBarang = cbto.getBarang();
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
        
        dataBarang,
            new String[]{
                "ID_Barang", "Nama_Barang", "Jenis_Barang", "Harga_Barang"
            }
        ));
        jScrolBarang.setViewportView(tbl_barang);
    }
    
    private void setDataAdmin(){
        ConvertAdminToObject cato = new ConvertAdminToObject();
        String [] [] dataAdmin = cato.getAdmin();
        tbl_admin.setModel(new javax.swing.table.DefaultTableModel(
        
        dataAdmin,
            new String[]{
                "ID_Admin", "Nama_Admin", "Username", "Password"
            }
        ));
        jScrolAdmin.setViewportView(tbl_admin);
    }
    
    private void setDataCustomer(){
        ConvertCustomerToObject ccto = new ConvertCustomerToObject();
        String [] [] dataCstmr = ccto.getCustomer();
        tblCus.setModel(new javax.swing.table.DefaultTableModel(
        
        dataCstmr,
            new String[]{
                "ID_Custumer", "Nama_Custumer","Alamt","No_Tlp","Email" ,"Username", "Password"
            }
        ));
        jScrollPaneCustomer.setViewportView(tblCus);
    }
    
    public void UpdateTbl(){
        ConvertCustomerToObject ccto = new ConvertCustomerToObject();
        String [] [] dataCstmr = ccto.getCustomer();
        tblCus.setModel(new javax.swing.table.DefaultTableModel(
        
        dataCstmr,
            new String[]{
                "ID_Custumer", "Nama_Custumer","Alamt","No_Tlp","Email" ,"Username", "Password"
            }
        ));
        jScrollPaneCustomer.setViewportView(tblCus);
        JOptionPane.showMessageDialog(null, " Data Sukses Di Update");
    }
    
    private void setDataTransaksi(){
        ConvertTransaksiToObject ctto = new ConvertTransaksiToObject();
        String [][] dataTran = ctto.getTransaksi();
        tbl_transaksi.setModel( new javax.swing.table.DefaultTableModel(
                
        dataTran,
            new String[]{
                "ID_Transaksi", "Total_Barang", "Total_Harga","Tangal","ID_Barang","ID_Custumer"
            }
        ));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Btn_databarang = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        PanelUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panelbrg = new javax.swing.JPanel();
        pnlInputdata = new javax.swing.JPanel();
        txt_IDBarang = new javax.swing.JTextField();
        txt_Namabarang = new javax.swing.JTextField();
        txt_JnsBarang = new javax.swing.JTextField();
        txt_HrgBarang = new javax.swing.JTextField();
        Lb_id = new javax.swing.JLabel();
        Lb_nama = new javax.swing.JLabel();
        Lb_jns = new javax.swing.JLabel();
        Lb_hrg = new javax.swing.JLabel();
        btn_insert = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        pnltabelBrg = new javax.swing.JPanel();
        jScrolBarang = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        PnlAdmin = new javax.swing.JPanel();
        PnlInput = new javax.swing.JPanel();
        Lb_idadmin = new javax.swing.JLabel();
        txt_idadmin = new javax.swing.JTextField();
        Lb_namaAdmin = new javax.swing.JLabel();
        txt_namaAdmin = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        Lb_username = new javax.swing.JLabel();
        Lb_pass = new javax.swing.JLabel();
        btn_createA = new javax.swing.JButton();
        btn_updateA = new javax.swing.JButton();
        btn_deleteA = new javax.swing.JButton();
        Pass = new javax.swing.JPasswordField();
        cbPassAdm = new javax.swing.JCheckBox();
        PnltabelAdmin = new javax.swing.JPanel();
        jScrolAdmin = new javax.swing.JScrollPane();
        tbl_admin = new javax.swing.JTable();
        PanelCustomer = new javax.swing.JPanel();
        PnlInputCus = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_namcus = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_usercus = new javax.swing.JTextField();
        btn_DeleteCus = new javax.swing.JButton();
        PassCus = new javax.swing.JPasswordField();
        txtID_cus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PnlTblCus = new javax.swing.JPanel();
        jScrollPaneCustomer = new javax.swing.JScrollPane();
        tblCus = new javax.swing.JTable();
        PnlTransaksi = new javax.swing.JPanel();
        PnltabelTransaksi = new javax.swing.JPanel();
        jScrollPaneTransaksi = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        Btn_databarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Btn_databarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Box.png"))); // NOI18N
        Btn_databarang.setText("Data Barang");
        Btn_databarang.setFocusable(false);
        Btn_databarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_databarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn_databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_databarangActionPerformed(evt);
            }
        });
        jToolBar1.add(Btn_databarang);

        btn_admin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-admin-64.png"))); // NOI18N
        btn_admin.setText("Data Admin");
        btn_admin.setFocusable(false);
        btn_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_admin);

        btnCustomer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-customer-64.png"))); // NOI18N
        btnCustomer.setText("Data Customer");
        btnCustomer.setFocusable(false);
        btnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCustomer);

        btn_transaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-transaction-list-64.png"))); // NOI18N
        btn_transaksi.setText("Data Transaksi");
        btn_transaksi.setFocusable(false);
        btn_transaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_transaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_transaksi);

        btn_exit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sign-out-64.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setFocusable(false);
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_exit);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, 90));

        PanelUtama.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Clarendon BT", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOBACCO SHOP");
        PanelUtama.add(jLabel1, "card2");

        pnlInputdata.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        pnlInputdata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_IDBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pnlInputdata.add(txt_IDBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, -1));

        txt_Namabarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pnlInputdata.add(txt_Namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, -1));

        txt_JnsBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pnlInputdata.add(txt_JnsBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, -1));

        txt_HrgBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pnlInputdata.add(txt_HrgBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));

        Lb_id.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_id.setText("ID Barang :");
        pnlInputdata.add(Lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Lb_nama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_nama.setText("Nama Barang :");
        pnlInputdata.add(Lb_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Lb_jns.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_jns.setText("Jenis Barang :");
        pnlInputdata.add(Lb_jns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Lb_hrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_hrg.setText("Harga Barang :");
        pnlInputdata.add(Lb_hrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btn_insert.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_insert.setText("Create");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        pnlInputdata.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 70, -1));

        btn_update.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        pnlInputdata.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 70, -1));

        btn_delete.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        pnlInputdata.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 70, -1));

        pnltabelBrg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tbl_barang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrolBarang.setViewportView(tbl_barang);

        javax.swing.GroupLayout pnltabelBrgLayout = new javax.swing.GroupLayout(pnltabelBrg);
        pnltabelBrg.setLayout(pnltabelBrgLayout);
        pnltabelBrgLayout.setHorizontalGroup(
            pnltabelBrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltabelBrgLayout.createSequentialGroup()
                .addComponent(jScrolBarang)
                .addContainerGap())
        );
        pnltabelBrgLayout.setVerticalGroup(
            pnltabelBrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltabelBrgLayout.createSequentialGroup()
                .addComponent(jScrolBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelbrgLayout = new javax.swing.GroupLayout(Panelbrg);
        Panelbrg.setLayout(PanelbrgLayout);
        PanelbrgLayout.setHorizontalGroup(
            PanelbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelbrgLayout.createSequentialGroup()
                .addComponent(pnlInputdata, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnltabelBrg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelbrgLayout.setVerticalGroup(
            PanelbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelbrgLayout.createSequentialGroup()
                .addComponent(pnlInputdata, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltabelBrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelUtama.add(Panelbrg, "cardBarang");

        PnlInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PnlInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lb_idadmin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_idadmin.setText("ID Admin :");
        PnlInput.add(Lb_idadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txt_idadmin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInput.add(txt_idadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, -1));

        Lb_namaAdmin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_namaAdmin.setText("Nama Admin :");
        PnlInput.add(Lb_namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txt_namaAdmin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInput.add(txt_namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, -1));

        txt_username.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInput.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, -1));

        Lb_username.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_username.setText("Username :");
        PnlInput.add(Lb_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        Lb_pass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lb_pass.setText("Password :");
        PnlInput.add(Lb_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btn_createA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_createA.setText("Create");
        btn_createA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createAActionPerformed(evt);
            }
        });
        PnlInput.add(btn_createA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btn_updateA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_updateA.setText("Update");
        btn_updateA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateAActionPerformed(evt);
            }
        });
        PnlInput.add(btn_updateA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        btn_deleteA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_deleteA.setText("Delete");
        btn_deleteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteAActionPerformed(evt);
            }
        });
        PnlInput.add(btn_deleteA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        Pass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInput.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, -1));

        cbPassAdm.setText("Show Password");
        cbPassAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPassAdmActionPerformed(evt);
            }
        });
        PnlInput.add(cbPassAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        tbl_admin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbl_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_adminMouseClicked(evt);
            }
        });
        jScrolAdmin.setViewportView(tbl_admin);

        javax.swing.GroupLayout PnltabelAdminLayout = new javax.swing.GroupLayout(PnltabelAdmin);
        PnltabelAdmin.setLayout(PnltabelAdminLayout);
        PnltabelAdminLayout.setHorizontalGroup(
            PnltabelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrolAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        PnltabelAdminLayout.setVerticalGroup(
            PnltabelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrolAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PnlAdminLayout = new javax.swing.GroupLayout(PnlAdmin);
        PnlAdmin.setLayout(PnlAdminLayout);
        PnlAdminLayout.setHorizontalGroup(
            PnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdminLayout.createSequentialGroup()
                .addComponent(PnlInput, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnltabelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlAdminLayout.setVerticalGroup(
            PnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInput, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .addComponent(PnltabelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelUtama.add(PnlAdmin, "cardAdmin");

        PanelCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Custumer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        PnlInputCus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nama Custumer :");
        PnlInputCus.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Alamat :");
        PnlInputCus.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("No_Telpon :");
        PnlInputCus.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Email :");
        PnlInputCus.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Username :");
        PnlInputCus.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Password :");
        PnlInputCus.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        txt_namcus.setEditable(false);
        txt_namcus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_namcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namcusActionPerformed(evt);
            }
        });
        PnlInputCus.add(txt_namcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 170, -1));

        txt_alamat.setEditable(false);
        txt_alamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInputCus.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, -1));

        txt_notelp.setEditable(false);
        txt_notelp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInputCus.add(txt_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, -1));

        txt_email.setEditable(false);
        txt_email.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInputCus.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 170, -1));

        txt_usercus.setEditable(false);
        txt_usercus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInputCus.add(txt_usercus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 170, -1));

        btn_DeleteCus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_DeleteCus.setText("Delete");
        btn_DeleteCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteCusActionPerformed(evt);
            }
        });
        PnlInputCus.add(btn_DeleteCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        PassCus.setEditable(false);
        PassCus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PnlInputCus.add(PassCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 170, -1));

        txtID_cus.setEditable(false);
        PnlInputCus.add(txtID_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 170, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("ID Custumer :");
        PnlInputCus.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        tblCus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblCus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCusMouseClicked(evt);
            }
        });
        jScrollPaneCustomer.setViewportView(tblCus);

        javax.swing.GroupLayout PnlTblCusLayout = new javax.swing.GroupLayout(PnlTblCus);
        PnlTblCus.setLayout(PnlTblCusLayout);
        PnlTblCusLayout.setHorizontalGroup(
            PnlTblCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCustomer, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PnlTblCusLayout.setVerticalGroup(
            PnlTblCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTblCusLayout.createSequentialGroup()
                .addComponent(jScrollPaneCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelCustomerLayout = new javax.swing.GroupLayout(PanelCustomer);
        PanelCustomer.setLayout(PanelCustomerLayout);
        PanelCustomerLayout.setHorizontalGroup(
            PanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInputCus, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addComponent(PnlTblCus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelCustomerLayout.setVerticalGroup(
            PanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCustomerLayout.createSequentialGroup()
                .addComponent(PnlInputCus, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlTblCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelUtama.add(PanelCustomer, "cardCostumer");

        PnltabelTransaksi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "History Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tbl_transaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_transaksiMouseClicked(evt);
            }
        });
        jScrollPaneTransaksi.setViewportView(tbl_transaksi);

        javax.swing.GroupLayout PnltabelTransaksiLayout = new javax.swing.GroupLayout(PnltabelTransaksi);
        PnltabelTransaksi.setLayout(PnltabelTransaksiLayout);
        PnltabelTransaksiLayout.setHorizontalGroup(
            PnltabelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        PnltabelTransaksiLayout.setVerticalGroup(
            PnltabelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnltabelTransaksiLayout.createSequentialGroup()
                .addComponent(jScrollPaneTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlTransaksiLayout = new javax.swing.GroupLayout(PnlTransaksi);
        PnlTransaksi.setLayout(PnlTransaksiLayout);
        PnlTransaksiLayout.setHorizontalGroup(
            PnlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnltabelTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlTransaksiLayout.setVerticalGroup(
            PnlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTransaksiLayout.createSequentialGroup()
                .addComponent(PnltabelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelUtama.add(PnlTransaksi, "cardTransaksi");

        getContentPane().add(PanelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_databarangActionPerformed
        cl = (CardLayout) PanelUtama.getLayout();
        cl.show(PanelUtama, "cardBarang");
    }//GEN-LAST:event_Btn_databarangActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        cl = (CardLayout) PanelUtama.getLayout();
        cl.show(PanelUtama, "cardAdmin");
    }//GEN-LAST:event_btn_adminActionPerformed

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        int row = tbl_barang.getSelectedRow();
        String ID_Barang = tbl_barang.getValueAt(row, 0).toString();
        String Nama_Barang = tbl_barang.getValueAt(row, 1).toString();
        String Jenis_Barang = tbl_barang.getValueAt(row, 2).toString();
        String Harga_Barang = tbl_barang.getValueAt(row, 3).toString();
        
        txt_IDBarang.setText(ID_Barang);
        txt_Namabarang.setText(Nama_Barang);
        txt_JnsBarang.setText(Jenis_Barang);
        txt_HrgBarang.setText(Harga_Barang);
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        String id_barang = txt_IDBarang.getText();
        String nama_barang = txt_Namabarang.getText();
        String jns_barang = txt_JnsBarang.getText();
        String strHrg_barang = txt_HrgBarang.getText();
        int Harga_Barang = Integer.parseInt(strHrg_barang);
        
        Barang brg = new Barang(id_barang, nama_barang, jns_barang, Harga_Barang);
        Execute.ExcuteBarang ebrg = new Execute.ExcuteBarang();
        int hasil = ebrg.insertBrg(brg);
        if (hasil > 0){
        JOptionPane.showMessageDialog(null, "Sukses Di Simpan");
            setDataBarang();
        }
        else{
          JOptionPane.showMessageDialog(null, "Failed Di Simpan");  
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String id_barang = txt_IDBarang.getText();
        Execute.ExcuteBarang ebrg = new Execute.ExcuteBarang();
         
          int hasil = ebrg.deleteBrg(id_barang);
          if (hasil > 0){
            JOptionPane.showMessageDialog(null, " Data Sukses Di Hapus");
                setDataBarang();
            }
            else{
              JOptionPane.showMessageDialog(null, "Data Failed Di Hapus");  
            }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String id_barang = txt_IDBarang.getText();
        String nama_barang = txt_Namabarang.getText();
        String jns_barang = txt_JnsBarang.getText();
        String strHrg_barang = txt_HrgBarang.getText();
        int Harga_Barang = Integer.parseInt(strHrg_barang);
        
        Barang brg = new Barang(id_barang, nama_barang, jns_barang, Harga_Barang);
        Execute.ExcuteBarang ebrg = new Execute.ExcuteBarang();
        int hasil = ebrg.updateBrg(brg);
        if (hasil > 0){
        JOptionPane.showMessageDialog(null, "Sukses Di Update");
            setDataBarang();
        }
        else{
          JOptionPane.showMessageDialog(null, "Failed Di Update");  
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tbl_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_adminMouseClicked
        int row = tbl_admin.getSelectedRow();
        String ID_admin = tbl_admin.getValueAt(row, 0).toString();
        String Nama_admin = tbl_admin.getValueAt(row, 1).toString();
        String Username = tbl_admin.getValueAt(row, 2).toString();
        String Password = tbl_admin.getValueAt(row, 3).toString();
        
        txt_idadmin.setText(ID_admin);
        txt_namaAdmin.setText(Nama_admin);
        txt_username.setText(Username);
        Pass.setText(Password);
    }//GEN-LAST:event_tbl_adminMouseClicked

    private void btn_createAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createAActionPerformed
        String id_admin= txt_idadmin.getText();
        String nama_admin = txt_namaAdmin.getText();
        String username = txt_username.getText();
        String password = Pass.getText();
        
        Admin adm = new Admin(id_admin, nama_admin, username, password);
        Execute.ExecAdmin eadm = new Execute.ExecAdmin();
        int hasil = eadm.insertAdm(adm);
        if (hasil > 0){
        JOptionPane.showMessageDialog(null, "Sukses Di Simpan");
            setDataAdmin();
        }
        else{
          JOptionPane.showMessageDialog(null, "Failed Di Simpan");  
        }
    }//GEN-LAST:event_btn_createAActionPerformed

    private void btn_updateAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateAActionPerformed
        String id_admin= txt_idadmin.getText();
        String nama_admin = txt_namaAdmin.getText();
        String username = txt_username.getText();
        String password = Pass.getText();
        
        Admin adm = new Admin(id_admin, nama_admin, username, password);
        Execute.ExecAdmin eadm = new Execute.ExecAdmin();
        int hasil = eadm.updateAdm(adm);
        if (hasil > 0){
        JOptionPane.showMessageDialog(null, "Sukses Di Update");
            setDataAdmin();
        }
        else{
          JOptionPane.showMessageDialog(null, "Failed Di Update");  
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateAActionPerformed

    private void btn_deleteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteAActionPerformed
        String id_admin = txt_idadmin.getText();
        Execute.ExecAdmin eAdm = new Execute.ExecAdmin();
         
          int hasil = eAdm.deleteAdmin(id_admin);
          if (hasil > 0){
            JOptionPane.showMessageDialog(null, " Data Sukses Di Hapus");
                setDataAdmin();
            }
            else{
              JOptionPane.showMessageDialog(null, "Data Failed Di Hapus");  
            }
    }//GEN-LAST:event_btn_deleteAActionPerformed

    private void tblCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCusMouseClicked
        int row = tblCus.getSelectedRow();
        String ID_Cus = tblCus.getValueAt(row, 0).toString();
        String Nama_Costumer = tblCus.getValueAt(row, 1).toString();
        String Alamat = tblCus.getValueAt(row, 2).toString();
        String NoTlp = tblCus.getValueAt(row, 3).toString();
        String Email = tblCus.getValueAt(row, 4).toString();
        String Username = tblCus.getValueAt(row, 5).toString();
        String Password = tblCus.getValueAt(row, 6).toString();

        txtID_cus.setText(ID_Cus);
        txt_namcus.setText(Nama_Costumer);
        txt_alamat.setText(Alamat);
        txt_notelp.setText(NoTlp);
        txt_email.setText(Email);
        txt_usercus.setText(Username);
        PassCus.setText(Password);
    }//GEN-LAST:event_tblCusMouseClicked

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        cl = (CardLayout) PanelUtama.getLayout();
        cl.show(PanelUtama, "cardCostumer");
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        cl = (CardLayout) PanelUtama.getLayout();
        cl.show(PanelUtama, "cardTransaksi");
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_DeleteCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteCusActionPerformed
        String id_cus = txtID_cus.getText();
        Execute.ExecutCustomer eCstm = new Execute.ExecutCustomer();
         
          int hasil = eCstm.deleteCustomer(id_cus);
          if (hasil > 0){
            JOptionPane.showMessageDialog(null, " Data Sukses Di Hapus");
                setDataCustomer();
            }
            else{
              JOptionPane.showMessageDialog(null, "Data Failed Di Hapus");  
            }
    }//GEN-LAST:event_btn_DeleteCusActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        GuiLogin gtbk = new GuiLogin();
        gtbk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed
    //tbl_TransaksiMouseClicked TIDAK DIGUNAKAN
    private void tbl_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_transaksiMouseClicked
        //
    }//GEN-LAST:event_tbl_transaksiMouseClicked
    //txt_namacusActionPerformed TIDAK DIGUNAKAN
    private void txt_namcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namcusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namcusActionPerformed

    private void cbPassAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPassAdmActionPerformed
        if (cbPassAdm.isSelected()) {
            Pass.setEchoChar((char)0);
        }
        else{
            Pass.setEchoChar('*');
        }
    }//GEN-LAST:event_cbPassAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAdmin().setVisible(true);
            }
        });
    }
    
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_databarang;
    private javax.swing.JLabel Lb_hrg;
    private javax.swing.JLabel Lb_id;
    private javax.swing.JLabel Lb_idadmin;
    private javax.swing.JLabel Lb_jns;
    private javax.swing.JLabel Lb_nama;
    private javax.swing.JLabel Lb_namaAdmin;
    private javax.swing.JLabel Lb_pass;
    private javax.swing.JLabel Lb_username;
    private javax.swing.JPanel PanelCustomer;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JPanel Panelbrg;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JPasswordField PassCus;
    private javax.swing.JPanel PnlAdmin;
    private javax.swing.JPanel PnlInput;
    private javax.swing.JPanel PnlInputCus;
    private javax.swing.JPanel PnlTblCus;
    private javax.swing.JPanel PnlTransaksi;
    private javax.swing.JPanel PnltabelAdmin;
    private javax.swing.JPanel PnltabelTransaksi;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btn_DeleteCus;
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_createA;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_deleteA;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_updateA;
    private javax.swing.JCheckBox cbPassAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrolAdmin;
    private javax.swing.JScrollPane jScrolBarang;
    private javax.swing.JScrollPane jScrollPaneCustomer;
    private javax.swing.JScrollPane jScrollPaneTransaksi;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlInputdata;
    private javax.swing.JPanel pnltabelBrg;
    private javax.swing.JTable tblCus;
    private javax.swing.JTable tbl_admin;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTable tbl_transaksi;
    private javax.swing.JTextField txtID_cus;
    private javax.swing.JTextField txt_HrgBarang;
    private javax.swing.JTextField txt_IDBarang;
    private javax.swing.JTextField txt_JnsBarang;
    private javax.swing.JTextField txt_Namabarang;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_idadmin;
    private javax.swing.JTextField txt_namaAdmin;
    private javax.swing.JTextField txt_namcus;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_usercus;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
