/*
-------------------------------------------------------------------
    NAMA    : M. INDRA GUNAWAN
    NRP     : 152020068
    KELAS   : BB Project Tugas Besar
-------------------------------------------------------------------
 */
package View;
import com.Login;
import com.ConvertBarangToObject;
import com.Transaksi;
import com.Customer;
import  Execute.ExecutTransaksi;
import Execute.ExecutCustomer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
public class GuiCustumer extends javax.swing.JFrame {

    public GuiCustumer() {
        initComponents();
        setDataBarang();
        
        this.setLocationRelativeTo(null);
    }
    private void setDataBarang(){
        ConvertBarangToObject cbto = new ConvertBarangToObject();
        String [] [] dataBarang = cbto.getBarang();
        tbl_BarangC.setModel(new javax.swing.table.DefaultTableModel(
        
        dataBarang,
            new String[]{
                "ID_Barang", "Nama_Barang", "Jenis_Barang", "Harga_Barang"
            }
        ));
        jScrollPaneBarang.setViewportView(tbl_BarangC);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_Profil = new javax.swing.JButton();
        btn_dftrbarang = new javax.swing.JButton();
        btn_trnsaksi = new javax.swing.JButton();
        btn_logOut = new javax.swing.JButton();
        PnlUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlProfil = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtpassP = new javax.swing.JTextField();
        txtIDuser = new javax.swing.JTextField();
        txtNamaUser = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNotlp = new javax.swing.JTextField();
        btn_edtProfil = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Pnlbarang = new javax.swing.JPanel();
        PnlTabel = new javax.swing.JPanel();
        jScrollPaneBarang = new javax.swing.JScrollPane();
        tbl_BarangC = new javax.swing.JTable();
        PnlBeli = new javax.swing.JPanel();
        txtIdbarang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txtJnsBarang = new javax.swing.JTextField();
        txtHrgBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_beli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTtlBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pnltransaksi = new javax.swing.JPanel();
        PnlPembelian = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNamaBrg = new javax.swing.JTextField();
        txtJnsBrg = new javax.swing.JTextField();
        txtHrgBrg = new javax.swing.JTextField();
        txtTtlBrg = new javax.swing.JTextField();
        txtTtlHrg = new javax.swing.JTextField();
        btn_Confirm = new javax.swing.JButton();
        txtIDbrg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dateChooserTgl = new datechooser.beans.DateChooserCombo();
        txtIdCus = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jToolBar1.setRollover(true);

        btn_Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-male-user-50.png"))); // NOI18N
        btn_Profil.setText("Profil");
        btn_Profil.setFocusable(false);
        btn_Profil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Profil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfilActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Profil);

        btn_dftrbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-open-parcel-50.png"))); // NOI18N
        btn_dftrbarang.setText("Daftar Barang");
        btn_dftrbarang.setFocusable(false);
        btn_dftrbarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dftrbarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dftrbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dftrbarangActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dftrbarang);

        btn_trnsaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-shopping-cart-50.png"))); // NOI18N
        btn_trnsaksi.setText("Transaksi");
        btn_trnsaksi.setFocusable(false);
        btn_trnsaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_trnsaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_trnsaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trnsaksiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_trnsaksi);

        btn_logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sign-out-50.png"))); // NOI18N
        btn_logOut.setText("Log Out");
        btn_logOut.setFocusable(false);
        btn_logOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_logOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_logOut);

        PnlUtama.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo tobacco shop.jpg"))); // NOI18N
        PnlUtama.add(jLabel1, "card2");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profil User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("ID User ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Nama User ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Alamat ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("No Telp");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("Email");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("Password");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("Username");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        txtpassP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtpassP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassPActionPerformed(evt);
            }
        });
        jPanel2.add(txtpassP, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 140, -1));

        txtIDuser.setEditable(false);
        txtIDuser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtIDuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        txtNamaUser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, -1));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, -1));

        txtUser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 140, -1));

        txtAlamat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 140, -1));

        txtNotlp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtNotlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 140, -1));

        btn_edtProfil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_edtProfil.setText("Edit Profil");
        btn_edtProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edtProfilActionPerformed(evt);
            }
        });
        jPanel2.add(btn_edtProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo tobacco shop.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 130, 840, 310));

        javax.swing.GroupLayout PnlProfilLayout = new javax.swing.GroupLayout(PnlProfil);
        PnlProfil.setLayout(PnlProfilLayout);
        PnlProfilLayout.setHorizontalGroup(
            PnlProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlProfilLayout.setVerticalGroup(
            PnlProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PnlUtama.add(PnlProfil, "carProfil");

        PnlTabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_BarangC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbl_BarangC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_BarangC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BarangCMouseClicked(evt);
            }
        });
        jScrollPaneBarang.setViewportView(tbl_BarangC);

        PnlTabel.add(jScrollPaneBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 200));

        PnlBeli.setBorder(javax.swing.BorderFactory.createTitledBorder("Pembelian Barang"));

        txtIdbarang.setEditable(false);
        txtIdbarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtnamabarang.setEditable(false);
        txtnamabarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtJnsBarang.setEditable(false);
        txtJnsBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtHrgBarang.setEditable(false);
        txtHrgBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("ID Barang : ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nama Barang :");

        btn_beli.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_beli.setText("Beli");
        btn_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beliActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Barang :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Harga Barang :");

        txtTtlBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Total Barang :");

        javax.swing.GroupLayout PnlBeliLayout = new javax.swing.GroupLayout(PnlBeli);
        PnlBeli.setLayout(PnlBeliLayout);
        PnlBeliLayout.setHorizontalGroup(
            PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBeliLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHrgBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtJnsBarang)))
                    .addComponent(txtTtlBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlBeliLayout.setVerticalGroup(
            PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtJnsBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTtlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_beli))
                    .addComponent(jLabel6))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlbarangLayout = new javax.swing.GroupLayout(Pnlbarang);
        Pnlbarang.setLayout(PnlbarangLayout);
        PnlbarangLayout.setHorizontalGroup(
            PnlbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
            .addGroup(PnlbarangLayout.createSequentialGroup()
                .addComponent(PnlBeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlbarangLayout.setVerticalGroup(
            PnlbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlbarangLayout.createSequentialGroup()
                .addComponent(PnlTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PnlUtama.add(Pnlbarang, "cardDftrbarang");

        PnlPembelian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Nama Barang :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Barang :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Harga Barang :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Total Barang :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Tanggal :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Total Harga :");

        txtNamaBrg.setEditable(false);
        txtNamaBrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtJnsBrg.setEditable(false);
        txtJnsBrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtHrgBrg.setEditable(false);
        txtHrgBrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtTtlBrg.setEditable(false);
        txtTtlBrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtTtlHrg.setEditable(false);
        txtTtlHrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btn_Confirm.setText("Confirmasi");
        btn_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmActionPerformed(evt);
            }
        });

        txtIDbrg.setEditable(false);
        txtIDbrg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("ID Barang :");

        dateChooserTgl.setNothingAllowed(false);
        dateChooserTgl.setFieldFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 12));

        txtIdCus.setEditable(false);
        txtIdCus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("ID Custumer :");

        javax.swing.GroupLayout PnlPembelianLayout = new javax.swing.GroupLayout(PnlPembelian);
        PnlPembelian.setLayout(PnlPembelianLayout);
        PnlPembelianLayout.setHorizontalGroup(
            PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPembelianLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlPembelianLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel13)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPembelianLayout.createSequentialGroup()
                        .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)))
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTtlHrg)
                    .addComponent(txtTtlBrg)
                    .addComponent(txtNamaBrg, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDbrg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlPembelianLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel21))
                .addGap(22, 22, 22)
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlPembelianLayout.createSequentialGroup()
                        .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJnsBrg, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtHrgBrg)
                            .addComponent(dateChooserTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(157, 157, 157))
                    .addGroup(PnlPembelianLayout.createSequentialGroup()
                        .addComponent(txtIdCus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Confirm)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PnlPembelianLayout.setVerticalGroup(
            PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPembelianLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8)
                    .addComponent(txtJnsBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtHrgBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtTtlBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addComponent(dateChooserTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtTtlHrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(btn_Confirm)))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnltransaksiLayout = new javax.swing.GroupLayout(Pnltransaksi);
        Pnltransaksi.setLayout(PnltransaksiLayout);
        PnltransaksiLayout.setHorizontalGroup(
            PnltransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnltransaksiLayout.setVerticalGroup(
            PnltransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnltransaksiLayout.createSequentialGroup()
                .addComponent(PnlPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        PnlUtama.add(Pnltransaksi, "cardTransaksi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dftrbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dftrbarangActionPerformed
        cl = (CardLayout) PnlUtama.getLayout();
        cl.show(PnlUtama, "cardDftrbarang");        

    }//GEN-LAST:event_btn_dftrbarangActionPerformed

    private void btn_trnsaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trnsaksiActionPerformed
         cl = (CardLayout) PnlUtama.getLayout();
         cl.show(PnlUtama, "cardTransaksi"); 
    }//GEN-LAST:event_btn_trnsaksiActionPerformed

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        GuiLogin gtbk = new GuiLogin();
        gtbk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logOutActionPerformed

    private void tbl_BarangCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BarangCMouseClicked

        int row = tbl_BarangC.getSelectedRow();
        String ID_Barang = tbl_BarangC.getValueAt(row, 0).toString();
        String Nama_Barang = tbl_BarangC.getValueAt(row, 1).toString();
        String Jenis_Barang = tbl_BarangC.getValueAt(row, 2).toString();
        String Harga_Barang = tbl_BarangC.getValueAt(row, 3).toString();
        
        txtIdbarang.setText(ID_Barang);
        txtnamabarang.setText(Nama_Barang);
        txtJnsBarang.setText(Jenis_Barang);
        txtHrgBarang.setText(Harga_Barang);        
    }//GEN-LAST:event_tbl_BarangCMouseClicked

    private void btn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beliActionPerformed
        int total = Integer.parseInt(txtHrgBarang.getText()) * Integer.parseInt(txtTtlBarang.getText());
        txtIDbrg.setText(txtIdbarang.getText());
        txtNamaBrg.setText(txtnamabarang.getText());
        txtJnsBrg.setText(txtJnsBarang.getText());
        txtHrgBrg.setText(txtHrgBarang.getText());
        txtTtlBrg.setText(txtTtlBarang.getText());
        txtTtlHrg.setText(String.valueOf(total));
        JOptionPane.showMessageDialog(null, "Barang Berhasil Di Simpan Di Transaksi");
    }//GEN-LAST:event_btn_beliActionPerformed

    private void btn_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmActionPerformed
        int totalbrg = Integer.parseInt(txtTtlBrg.getText()) ;
        int totalhrg = Integer.parseInt(txtTtlHrg.getText());
        String tanggal = dateChooserTgl.getText();
        String idbrg = txtIDbrg.getText();
        int idCtm = Integer.parseInt(txtIdCus.getText());
        
        Transaksi tran = new Transaksi(totalbrg, totalhrg,tanggal,idbrg,idCtm);
        Execute.ExecutTransaksi eTran = new Execute.ExecutTransaksi();
        int hasil = eTran.insertTrans(tran);
        if (hasil > 0){
        JOptionPane.showMessageDialog(null, "Transaksi Sukses");
        }
        else{
            
          JOptionPane.showMessageDialog(null, "Transaksi Failed");  
        }
    }//GEN-LAST:event_btn_ConfirmActionPerformed

    private void btn_ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfilActionPerformed
        cl = (CardLayout) PnlUtama.getLayout();
        cl.show(PnlUtama, "carProfil"); 
    }//GEN-LAST:event_btn_ProfilActionPerformed

    private void btn_edtProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edtProfilActionPerformed
        String strid_user = txtIDuser.getText();
        int IdUser = Integer.parseInt(strid_user);
        String nama_user = txtNamaUser.getText();
        String email = txtEmail.getText();
        String alamat = txtAlamat.getText();
        String notlp = txtNotlp.getText();
        String User = txtUser.getText();
        String Pass = txtpassP.getText();
       
        Customer Cstm = new Customer(IdUser, nama_user, alamat, notlp, email, User, Pass);
        Execute.ExecutCustomer eCstm = new Execute.ExecutCustomer();
        int hasil = eCstm.updateCstmr(IdUser, nama_user, alamat, notlp, email, User, Pass);
        if (hasil > 0){
        JOptionPane.showMessageDialog(null, "Perubahan Berhasil, Silahkan Keluar dan Masuk Kembali");
       }
        else{
          JOptionPane.showMessageDialog(null, "Perubahan Gagal");  
        }
    }//GEN-LAST:event_btn_edtProfilActionPerformed

    private void txtpassPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassPActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtIDuser.setText(String.valueOf(Login.getID_Custumer()));
        txtNamaUser.setText((Login.getNama_Custumer()));
        txtEmail.setText(Login.getEmail());
        txtAlamat.setText(Login.getAlamat());
        txtNotlp.setText(Login.getNo_Tlp());
        txtUser.setText(Login.getUser());
        txtpassP.setText(Login.getPass());
        txtIdCus.setText(String.valueOf(Login.getID_Custumer()));
    }//GEN-LAST:event_formWindowActivated

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCustumer().setVisible(true);
            }
        });
    }
    
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBeli;
    private javax.swing.JPanel PnlPembelian;
    private javax.swing.JPanel PnlProfil;
    private javax.swing.JPanel PnlTabel;
    private javax.swing.JPanel PnlUtama;
    private javax.swing.JPanel Pnlbarang;
    private javax.swing.JPanel Pnltransaksi;
    private javax.swing.JButton btn_Confirm;
    private javax.swing.JButton btn_Profil;
    private javax.swing.JButton btn_beli;
    private javax.swing.JButton btn_dftrbarang;
    private javax.swing.JButton btn_edtProfil;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JButton btn_trnsaksi;
    private datechooser.beans.DateChooserCombo dateChooserTgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneBarang;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_BarangC;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHrgBarang;
    private javax.swing.JTextField txtHrgBrg;
    private javax.swing.JTextField txtIDbrg;
    private javax.swing.JTextField txtIDuser;
    private javax.swing.JTextField txtIdCus;
    private javax.swing.JTextField txtIdbarang;
    private javax.swing.JTextField txtJnsBarang;
    private javax.swing.JTextField txtJnsBrg;
    private javax.swing.JTextField txtNamaBrg;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JTextField txtNotlp;
    private javax.swing.JTextField txtTtlBarang;
    private javax.swing.JTextField txtTtlBrg;
    private javax.swing.JTextField txtTtlHrg;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtpassP;
    // End of variables declaration//GEN-END:variables
}
